# Generated by Django 6.0.2 on 2026-02-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathar_name',
            field=models.TextField(default='Rahim Uddin'),
        ),
    ]
